// Generated by CoffeeScript 1.3.1
(function() {

  define(function() {
    var Pubsub;
    Pubsub = (function() {

      function Pubsub() {}

      Pubsub.singleton = function() {
        var _ref;
        return (_ref = this.instance) != null ? _ref : this.instance = new this();
      };

      Pubsub.prototype.subscriptions = [];

      Pubsub.prototype.subscribe = function(name, callback) {
        this.subscriptions.push({
          name: name,
          callback: callback
        });
        return [name, callback];
      };

      Pubsub.prototype.unsubscribe = function(args) {
        var i, sub, subs, _i, _len, _results;
        subs = this.subscriptions;
        _results = [];
        for (i = _i = 0, _len = subs.length; _i < _len; i = ++_i) {
          sub = subs[i];
          if (sub.name === args[0] && sub.callback === args[1]) {
            _results.push(subs.splice(i, 1));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      Pubsub.prototype.publish = function(name, args) {
        var sub, subs, temp, temps, _i, _j, _len, _len1, _results;
        temps = [];
        subs = this.subscriptions;
        if (subs.length > 0) {
          for (_i = 0, _len = subs.length; _i < _len; _i++) {
            sub = subs[_i];
            if (sub.name = name) {
              temps.push({
                fn: sub.callback
              });
            }
          }
          _results = [];
          for (_j = 0, _len1 = temps.length; _j < _len1; _j++) {
            temp = temps[_j];
            _results.push(temp.fn.apply(this, [args]));
          }
          return _results;
        }
      };

      return Pubsub;

    })();
    return Pubsub.singleton();
  });

}).call(this);
